/**
 * This file is automatically generated.
 * Do not modify! -- ALL CHANGES WILL BE ERASED!
 */

package com.example;

import java.util.Date;

/**
 * Provides project version information.
 */
public final class GeneratedVersion {
    public static final String PROJECT = "Sample";
    public static final Date BUILD_DATE = new Date(1743188866063L);
    public static final int MAJOR = 1;
    public static final int MINOR = 0;
    public static final int REVISION = 1;
    public static final String QUALIFIER = "rc1";
    public static final String VERSION = "1.0.1-rc1";

    /**
     * Disables the default constructor.
     */
    private GeneratedVersion() {
        throw new UnsupportedOperationException("Illegal constructor call.");
    }
}
